"""
Semi-realistic 100-node web graph for crawl-prioritization experiments.
"""

GRAPH = {
    # ── Major news / reference pages ──────────────────────────────────────
    "bbc.com":            ["cnn.com", "nytimes.com", "bbc.com/news", "reuters.com", "wikipedia.org"],
    "bbc.com/news":       ["bbc.com", "reuters.com", "theguardian.com", "apnews.com"],
    "cnn.com":            ["bbc.com", "reuters.com", "nytimes.com", "cnn.com/world", "wikipedia.org"],
    "cnn.com/world":      ["bbc.com", "nytimes.com", "theguardian.com"],
    "nytimes.com":        ["cnn.com", "theguardian.com", "reuters.com", "washingtonpost.com"],
    "reuters.com":        ["bbc.com", "bloomberg.com", "nytimes.com", "apnews.com"],
    "theguardian.com":    ["bbc.com", "cnn.com", "medium.com", "wikipedia.org"],
    "bloomberg.com":      ["reuters.com", "wsj.com", "ft.com"],
    "wsj.com":            ["bloomberg.com", "reuters.com", "ft.com"],
    "ft.com":             ["wsj.com", "bloomberg.com", "economist.com"],
    "economist.com":      ["ft.com", "bbc.com", "reuters.com"],
    "apnews.com":         ["reuters.com", "bbc.com", "npr.org"],
    "washingtonpost.com": ["nytimes.com", "cnn.com", "apnews.com"],
    "npr.org":            ["bbc.com", "apnews.com", "wikipedia.org"],
    "aljazeera.com":      ["bbc.com", "reuters.com", "un.org"],
    "vox.com":            ["nytimes.com", "washingtonpost.com", "medium.com"],
    "theatlantic.com":    ["nytimes.com", "theguardian.com", "medium.com"],
    "politico.com":       ["nytimes.com", "washingtonpost.com", "cnn.com"],
    "foreignpolicy.com":  ["economist.com", "un.org", "washingtonpost.com"],
    "techcrunch.com":     ["wired.com", "theverge.com", "github.com/open-source-project"],
    "wired.com":          ["techcrunch.com", "theverge.com", "arxiv.org"],
    "theverge.com":       ["techcrunch.com", "wired.com", "wikipedia.org"],

    # ── Scientific / health ───────────────────────────────────────────────
    "wikipedia.org":      ["bbc.com", "cnn.com", "nytimes.com", "reuters.com", "arxiv.org"],
    "arxiv.org":          ["wikipedia.org", "nature.com", "mit.edu"],
    "nature.com":         ["arxiv.org", "science.org", "nih.gov"],
    "science.org":        ["nature.com", "nih.gov", "who.int"],
    "nih.gov":            ["who.int", "cdc.gov", "nature.com"],
    "who.int":            ["nih.gov", "cdc.gov", "un.org"],
    "cdc.gov":            ["nih.gov", "who.int", "mayoclinic.org"],
    "pubmed.ncbi.nlm.nih.gov": ["nih.gov", "nature.com", "science.org"],
    "thelancet.com":      ["nature.com", "nih.gov", "who.int"],
    "nejm.org":           ["nih.gov", "nature.com", "cdc.gov"],
    "mayoclinic.org":     ["cdc.gov", "nih.gov", "healthline.com"],
    "healthline.com":     ["mayoclinic.org", "webmd.com", "nih.gov"],
    "webmd.com":          ["healthline.com", "mayoclinic.org", "verywellhealth.com"],
    "verywellhealth.com": ["webmd.com", "healthline.com", "mayoclinic.org"],
    "medlineplus.gov":    ["nih.gov", "cdc.gov", "mayoclinic.org"],

    # ── Intergovernmental / policy ────────────────────────────────────────
    "un.org":             ["who.int", "worldbank.org", "wikipedia.org"],
    "worldbank.org":      ["un.org", "imf.org", "oecd.org"],
    "imf.org":            ["worldbank.org", "oecd.org", "ecb.europa.eu"],
    "oecd.org":           ["worldbank.org", "imf.org", "gov.uk"],
    "ecb.europa.eu":      ["imf.org", "worldbank.org", "ft.com"],
    "europa.eu":          ["oecd.org", "ecb.europa.eu", "un.org"],
    "gov.uk":             ["nhs.uk", "oecd.org", "bbc.com"],
    "nhs.uk":             ["gov.uk", "who.int", "mayoclinic.org"],
    "data.gov":           ["gov.uk", "worldbank.org", "nih.gov"],

    # ── University / educational ──────────────────────────────────────────
    "mit.edu":            ["stanford.edu", "arxiv.org", "wikipedia.org"],
    "stanford.edu":       ["mit.edu", "arxiv.org", "cs.cmu.edu"],
    "cs.cmu.edu":         ["stanford.edu", "mit.edu", "github.com/open-source-project"],
    "harvard.edu":        ["mit.edu", "stanford.edu", "nature.com"],
    "cambridge.org":      ["nature.com", "arxiv.org", "wikipedia.org"],
    "ox.ac.uk":           ["cambridge.org", "nature.com", "bbc.com"],
    "khanacademy.org":    ["wikipedia.org", "mit.edu", "docs.python.org"],
    "coursera.org":       ["stanford.edu", "mit.edu", "khanacademy.org"],
    "edx.org":            ["mit.edu", "harvard.edu", "coursera.org"],

    # ── Technical / developer ─────────────────────────────────────────────
    "github.com/open-source-project": ["docs.python.org", "stackoverflow.com", "pypi.org"],
    "docs.python.org":    ["pypi.org", "github.com/open-source-project", "stackoverflow.com"],
    "pypi.org":           ["docs.python.org", "github.com/open-source-project"],
    "stackoverflow.com":  ["docs.python.org", "github.com/open-source-project", "medium.com/ai"],
    "developer.mozilla.org": ["docs.python.org", "stackoverflow.com", "github.com/open-source-project"],
    "docs.docker.com":    ["github.com/open-source-project", "stackoverflow.com", "developer.mozilla.org"],
    "kubernetes.io":      ["docs.docker.com", "github.com/open-source-project", "stackoverflow.com"],
    "tensorflow.org":     ["arxiv.org", "github.com/open-source-project", "docs.python.org"],
    "pytorch.org":        ["arxiv.org", "github.com/open-source-project", "tensorflow.org"],
    "huggingface.co":     ["arxiv.org", "pytorch.org", "tensorflow.org"],

    # ── Mixed-quality blogs / community ───────────────────────────────────
    "medium.com":         ["bbc.com", "cnn.com", "medium.com/ai", "randomblog123.com"],
    "medium.com/ai":      ["arxiv.org", "github.com/open-source-project", "towardsdatascience.com"],
    "towardsdatascience.com": ["medium.com/ai", "kaggle.com", "arxiv.org"],
    "kaggle.com":         ["towardsdatascience.com", "github.com/open-source-project", "arxiv.org"],
    "substack.com/tech":  ["arxiv.org", "medium.com/ai", "reuters.com"],
    "dev.to":             ["stackoverflow.com", "github.com/open-source-project", "medium.com/ai"],
    "hashnode.dev":       ["dev.to", "medium.com/ai", "github.com/open-source-project"],
    "personalblog.dev":   ["github.com/open-source-project", "medium.com/ai", "docs.python.org"],
    "lesswrong.com":      ["arxiv.org", "medium.com/ai", "wikipedia.org"],
    "reddit.com/r/machinelearning": ["arxiv.org", "medium.com/ai", "huggingface.co"],
    "news.ycombinator.com": ["techcrunch.com", "wired.com", "github.com/open-source-project"],

    # ── Low quality / junk ───────────────────────────────────────────────
    "randomblog123.com":  ["login.site.com", "medium.com", "clickbaitnews.net"],
    "clickbaitnews.net":  ["randomblog123.com", "forumspam.net", "shoppingcart.com"],
    "forumspam.net":      ["login.site.com", "shoppingcart.com", "clickbaitnews.net"],
    "buzzfeedarticle.click": ["clickbaitnews.net", "randomblog123.com", "shoppingcart.com"],
    "articlefarm.xyz":    ["clickbaitnews.net", "forumspam.net"],

    # ── Utility / blocked pages ───────────────────────────────────────────
    "login.site.com":     [],
    "signup.site.com":    [],
    "account.site.com":   ["login.site.com"],
    "shoppingcart.com":   ["checkout.com", "product123.store/item1"],
    "checkout.com":       [],
    "product123.store/item1":    ["product123.store/reviews", "shoppingcart.com"],
    "product123.store/reviews":  ["product123.store/item1", "forumspam.net"],
    "newsletter.site.com/unsubscribe": [],
    "ads.tracker.com":    [],
    "cdn.assets.com":     [],
}

# Precomputed PageRank-style authority scores
PAGERANK = {
    "bbc.com": 0.95, "bbc.com/news": 0.83,
    "cnn.com": 0.91, "cnn.com/world": 0.79,
    "nytimes.com": 0.89, "reuters.com": 0.93,
    "theguardian.com": 0.78, "bloomberg.com": 0.82,
    "wsj.com": 0.80, "ft.com": 0.76,
    "economist.com": 0.74, "apnews.com": 0.77,
    "washingtonpost.com": 0.75, "npr.org": 0.71,
    "aljazeera.com": 0.73, "vox.com": 0.65,
    "theatlantic.com": 0.68, "politico.com": 0.70,
    "foreignpolicy.com": 0.64, "techcrunch.com": 0.72,
    "wired.com": 0.69, "theverge.com": 0.67,
    "wikipedia.org": 0.97, "arxiv.org": 0.86,
    "nature.com": 0.84, "science.org": 0.81,
    "nih.gov": 0.85, "who.int": 0.83,
    "cdc.gov": 0.80, "pubmed.ncbi.nlm.nih.gov": 0.82,
    "thelancet.com": 0.79, "nejm.org": 0.81,
    "un.org": 0.79, "worldbank.org": 0.78,
    "imf.org": 0.76, "oecd.org": 0.73,
    "ecb.europa.eu": 0.71, "europa.eu": 0.74,
    "gov.uk": 0.75, "nhs.uk": 0.77,
    "data.gov": 0.70, "mayoclinic.org": 0.74,
    "healthline.com": 0.66, "webmd.com": 0.64,
    "verywellhealth.com": 0.61, "medlineplus.gov": 0.72,
    "mit.edu": 0.79, "stanford.edu": 0.78,
    "cs.cmu.edu": 0.72, "harvard.edu": 0.80,
    "cambridge.org": 0.77, "ox.ac.uk": 0.75,
    "khanacademy.org": 0.68, "coursera.org": 0.66,
    "edx.org": 0.65,
    "github.com/open-source-project": 0.69,
    "docs.python.org": 0.73, "pypi.org": 0.65,
    "stackoverflow.com": 0.70, "developer.mozilla.org": 0.71,
    "docs.docker.com": 0.64, "kubernetes.io": 0.66,
    "tensorflow.org": 0.72, "pytorch.org": 0.73,
    "huggingface.co": 0.75,
    "medium.com": 0.58, "medium.com/ai": 0.63,
    "towardsdatascience.com": 0.57, "kaggle.com": 0.60,
    "substack.com/tech": 0.50, "dev.to": 0.55,
    "hashnode.dev": 0.48, "personalblog.dev": 0.42,
    "lesswrong.com": 0.52, "reddit.com/r/machinelearning": 0.60,
    "news.ycombinator.com": 0.65,
    "randomblog123.com": 0.18, "clickbaitnews.net": 0.14,
    "forumspam.net": 0.09, "buzzfeedarticle.click": 0.12,
    "articlefarm.xyz": 0.08,
    "login.site.com": 0.03, "signup.site.com": 0.03,
    "account.site.com": 0.04, "shoppingcart.com": 0.07,
    "checkout.com": 0.02, "product123.store/item1": 0.08,
    "product123.store/reviews": 0.05,
    "newsletter.site.com/unsubscribe": 0.01,
    "ads.tracker.com": 0.02, "cdn.assets.com": 0.01,
}

# Crawl-allowed pages (utility/blocked pages excluded, mimicking robots.txt)
ALLOWED = {
    "bbc.com", "bbc.com/news", "cnn.com", "cnn.com/world", "nytimes.com", "reuters.com",
    "theguardian.com", "bloomberg.com", "wsj.com", "ft.com", "economist.com", "apnews.com",
    "washingtonpost.com", "npr.org", "aljazeera.com", "vox.com", "theatlantic.com",
    "politico.com", "foreignpolicy.com", "techcrunch.com", "wired.com", "theverge.com",
    "wikipedia.org", "arxiv.org", "nature.com", "science.org", "nih.gov", "who.int",
    "cdc.gov", "pubmed.ncbi.nlm.nih.gov", "thelancet.com", "nejm.org",
    "un.org", "worldbank.org", "imf.org", "oecd.org", "ecb.europa.eu", "europa.eu",
    "gov.uk", "nhs.uk", "data.gov", "mayoclinic.org", "healthline.com", "webmd.com",
    "verywellhealth.com", "medlineplus.gov",
    "mit.edu", "stanford.edu", "cs.cmu.edu", "harvard.edu", "cambridge.org", "ox.ac.uk",
    "khanacademy.org", "coursera.org", "edx.org",
    "github.com/open-source-project", "docs.python.org", "pypi.org", "stackoverflow.com",
    "developer.mozilla.org", "docs.docker.com", "kubernetes.io",
    "tensorflow.org", "pytorch.org", "huggingface.co",
    "medium.com", "medium.com/ai", "towardsdatascience.com", "kaggle.com",
    "substack.com/tech", "dev.to", "hashnode.dev", "personalblog.dev",
    "lesswrong.com", "reddit.com/r/machinelearning", "news.ycombinator.com",
    "randomblog123.com", "clickbaitnews.net",
}

# Estimated content quality prior  (0–1)
CONTENT_QUALITY = {
    "bbc.com": 0.95, "bbc.com/news": 0.93,
    "cnn.com": 0.88, "cnn.com/world": 0.87,
    "nytimes.com": 0.94, "reuters.com": 0.96,
    "theguardian.com": 0.86, "bloomberg.com": 0.89,
    "wsj.com": 0.88, "ft.com": 0.87,
    "economist.com": 0.90, "apnews.com": 0.88,
    "washingtonpost.com": 0.86, "npr.org": 0.90,
    "aljazeera.com": 0.84, "vox.com": 0.78,
    "theatlantic.com": 0.82, "politico.com": 0.80,
    "foreignpolicy.com": 0.81, "techcrunch.com": 0.78,
    "wired.com": 0.80, "theverge.com": 0.76,
    "wikipedia.org": 0.84, "arxiv.org": 0.95,
    "nature.com": 0.96, "science.org": 0.95,
    "nih.gov": 0.94, "who.int": 0.94,
    "cdc.gov": 0.92, "pubmed.ncbi.nlm.nih.gov": 0.95,
    "thelancet.com": 0.94, "nejm.org": 0.95,
    "un.org": 0.88, "worldbank.org": 0.90,
    "imf.org": 0.88, "oecd.org": 0.87,
    "ecb.europa.eu": 0.85, "europa.eu": 0.86,
    "gov.uk": 0.90, "nhs.uk": 0.92,
    "data.gov": 0.88, "mayoclinic.org": 0.89,
    "healthline.com": 0.74, "webmd.com": 0.70,
    "verywellhealth.com": 0.68, "medlineplus.gov": 0.90,
    "mit.edu": 0.93, "stanford.edu": 0.93,
    "cs.cmu.edu": 0.89, "harvard.edu": 0.93,
    "cambridge.org": 0.91, "ox.ac.uk": 0.90,
    "khanacademy.org": 0.85, "coursera.org": 0.80,
    "edx.org": 0.80,
    "github.com/open-source-project": 0.80,
    "docs.python.org": 0.94, "pypi.org": 0.76,
    "stackoverflow.com": 0.72, "developer.mozilla.org": 0.88,
    "docs.docker.com": 0.82, "kubernetes.io": 0.84,
    "tensorflow.org": 0.88, "pytorch.org": 0.89,
    "huggingface.co": 0.85,
    "medium.com": 0.60, "medium.com/ai": 0.73,
    "towardsdatascience.com": 0.70, "kaggle.com": 0.78,
    "substack.com/tech": 0.66, "dev.to": 0.65,
    "hashnode.dev": 0.60, "personalblog.dev": 0.58,
    "lesswrong.com": 0.68, "reddit.com/r/machinelearning": 0.65,
    "news.ycombinator.com": 0.70,
    "randomblog123.com": 0.24, "clickbaitnews.net": 0.12,
    "forumspam.net": 0.03, "buzzfeedarticle.click": 0.15,
    "articlefarm.xyz": 0.10,
    "login.site.com": 0.02, "signup.site.com": 0.02,
    "account.site.com": 0.03, "shoppingcart.com": 0.05,
    "checkout.com": 0.01, "product123.store/item1": 0.08,
    "product123.store/reviews": 0.06,
    "newsletter.site.com/unsubscribe": 0.01,
    "ads.tracker.com": 0.01, "cdn.assets.com": 0.01,
}


def get_web_data():
    """Return all experiment data structures."""
    return GRAPH, PAGERANK, ALLOWED, CONTENT_QUALITY


if __name__ == "__main__":
    print(f"Nodes: {len(GRAPH)}")
    print(f"Allowed pages: {len(ALLOWED)}")
