"""
Semi-realistic 50-node web graph for crawl-prioritization experiments.

This file keeps the dataset separate from the ranking code so you can import it
from another script and inspect / reuse the data easily.
"""

GRAPH = {
    # Major news / reference pages
    "bbc.com": ["cnn.com", "nytimes.com", "bbc.com/news", "reuters.com", "wikipedia.org"],
    "bbc.com/news": ["bbc.com", "reuters.com", "theguardian.com", "apnews.com"],
    "cnn.com": ["bbc.com", "reuters.com", "nytimes.com", "cnn.com/world", "wikipedia.org"],
    "cnn.com/world": ["bbc.com", "nytimes.com", "theguardian.com"],
    "nytimes.com": ["cnn.com", "theguardian.com", "reuters.com", "washingtonpost.com"],
    "reuters.com": ["bbc.com", "bloomberg.com", "nytimes.com", "apnews.com"],
    "theguardian.com": ["bbc.com", "cnn.com", "medium.com", "wikipedia.org"],
    "bloomberg.com": ["reuters.com", "wsj.com", "ft.com"],
    "wsj.com": ["bloomberg.com", "reuters.com", "ft.com"],
    "ft.com": ["wsj.com", "bloomberg.com", "economist.com"],
    "economist.com": ["ft.com", "bbc.com", "reuters.com"],
    "apnews.com": ["reuters.com", "bbc.com", "npr.org"],
    "washingtonpost.com": ["nytimes.com", "cnn.com", "apnews.com"],
    "npr.org": ["bbc.com", "apnews.com", "wikipedia.org"],
    "wikipedia.org": ["bbc.com", "cnn.com", "nytimes.com", "reuters.com", "arxiv.org"],
    "arxiv.org": ["wikipedia.org", "nature.com", "mit.edu"],
    "nature.com": ["arxiv.org", "science.org", "nih.gov"],
    "science.org": ["nature.com", "nih.gov", "who.int"],
    "nih.gov": ["who.int", "cdc.gov", "nature.com"],
    "who.int": ["nih.gov", "cdc.gov", "un.org"],
    "cdc.gov": ["nih.gov", "who.int", "mayoclinic.org"],
    "un.org": ["who.int", "worldbank.org", "wikipedia.org"],
    "worldbank.org": ["un.org", "imf.org", "oecd.org"],
    "imf.org": ["worldbank.org", "oecd.org", "ecb.europa.eu"],
    "oecd.org": ["worldbank.org", "imf.org", "gov.uk"],
    "gov.uk": ["nhs.uk", "oecd.org", "bbc.com"],
    "nhs.uk": ["gov.uk", "who.int", "mayoclinic.org"],
    "mayoclinic.org": ["cdc.gov", "nih.gov", "healthline.com"],
    "healthline.com": ["mayoclinic.org", "webmd.com", "nih.gov"],
    "webmd.com": ["healthline.com", "mayoclinic.org", "verywellhealth.com"],
    "verywellhealth.com": ["webmd.com", "healthline.com", "mayoclinic.org"],

    # University / educational / technical pages
    "mit.edu": ["stanford.edu", "arxiv.org", "wikipedia.org"],
    "stanford.edu": ["mit.edu", "arxiv.org", "cs.cmu.edu"],
    "cs.cmu.edu": ["stanford.edu", "mit.edu", "github.com/open-source-project"],
    "github.com/open-source-project": ["docs.python.org", "stackoverflow.com", "pypi.org"],
    "docs.python.org": ["pypi.org", "github.com/open-source-project", "stackoverflow.com"],
    "pypi.org": ["docs.python.org", "github.com/open-source-project"],
    "stackoverflow.com": ["docs.python.org", "github.com/open-source-project", "medium.com/ai"],

    # Blogs / mixed quality content pages
    "medium.com": ["bbc.com", "cnn.com", "medium.com/ai", "randomblog123.com"],
    "medium.com/ai": ["arxiv.org", "github.com/open-source-project", "towardsdatascience.com"],
    "towardsdatascience.com": ["medium.com/ai", "kaggle.com", "arxiv.org"],
    "kaggle.com": ["towardsdatascience.com", "github.com/open-source-project", "arxiv.org"],
    "substack.com/tech": ["arxiv.org", "medium.com/ai", "reuters.com"],
    "personalblog.dev": ["github.com/open-source-project", "medium.com/ai", "docs.python.org"],
    "randomblog123.com": ["login.site.com", "medium.com", "clickbaitnews.net"],
    "clickbaitnews.net": ["randomblog123.com", "forumspam.net", "shoppingcart.com"],
    "forumspam.net": ["login.site.com", "shoppingcart.com", "clickbaitnews.net"],

    # Utility / junk / low-value pages
    "login.site.com": [],
    "signup.site.com": [],
    "account.site.com": ["login.site.com"],
    "shoppingcart.com": ["checkout.com", "product123.store/item1"],
    "checkout.com": [],
    "product123.store/item1": ["product123.store/reviews", "shoppingcart.com"],
    "product123.store/reviews": ["product123.store/item1", "forumspam.net"],
}

# Precomputed PageRank-style authority scores.
PAGERANK = {
    "bbc.com": 0.95,
    "bbc.com/news": 0.83,
    "cnn.com": 0.91,
    "cnn.com/world": 0.79,
    "nytimes.com": 0.89,
    "reuters.com": 0.93,
    "theguardian.com": 0.78,
    "bloomberg.com": 0.82,
    "wsj.com": 0.80,
    "ft.com": 0.76,
    "economist.com": 0.74,
    "apnews.com": 0.77,
    "washingtonpost.com": 0.75,
    "npr.org": 0.71,
    "wikipedia.org": 0.97,
    "arxiv.org": 0.86,
    "nature.com": 0.84,
    "science.org": 0.81,
    "nih.gov": 0.85,
    "who.int": 0.83,
    "cdc.gov": 0.80,
    "un.org": 0.79,
    "worldbank.org": 0.78,
    "imf.org": 0.76,
    "oecd.org": 0.73,
    "gov.uk": 0.75,
    "nhs.uk": 0.77,
    "mayoclinic.org": 0.74,
    "healthline.com": 0.66,
    "webmd.com": 0.64,
    "verywellhealth.com": 0.61,
    "mit.edu": 0.79,
    "stanford.edu": 0.78,
    "cs.cmu.edu": 0.72,
    "github.com/open-source-project": 0.69,
    "docs.python.org": 0.73,
    "pypi.org": 0.65,
    "stackoverflow.com": 0.70,
    "medium.com": 0.58,
    "medium.com/ai": 0.63,
    "towardsdatascience.com": 0.57,
    "kaggle.com": 0.60,
    "substack.com/tech": 0.50,
    "personalblog.dev": 0.42,
    "randomblog123.com": 0.18,
    "clickbaitnews.net": 0.14,
    "forumspam.net": 0.09,
    "login.site.com": 0.03,
    "signup.site.com": 0.03,
    "account.site.com": 0.04,
    "shoppingcart.com": 0.07,
    "checkout.com": 0.02,
    "product123.store/item1": 0.08,
    "product123.store/reviews": 0.05,
}

# Crawl-allowed pages. Utility pages are intentionally excluded to mimic robots restrictions.
ALLOWED = {
    "bbc.com", "bbc.com/news", "cnn.com", "cnn.com/world", "nytimes.com", "reuters.com",
    "theguardian.com", "bloomberg.com", "wsj.com", "ft.com", "economist.com", "apnews.com",
    "washingtonpost.com", "npr.org", "wikipedia.org", "arxiv.org", "nature.com", "science.org",
    "nih.gov", "who.int", "cdc.gov", "un.org", "worldbank.org", "imf.org", "oecd.org",
    "gov.uk", "nhs.uk", "mayoclinic.org", "healthline.com", "webmd.com", "verywellhealth.com",
    "mit.edu", "stanford.edu", "cs.cmu.edu", "github.com/open-source-project", "docs.python.org",
    "pypi.org", "stackoverflow.com", "medium.com", "medium.com/ai", "towardsdatascience.com",
    "kaggle.com", "substack.com/tech", "personalblog.dev", "randomblog123.com", "clickbaitnews.net",
}

# Estimated content quality prior.
CONTENT_QUALITY = {
    "bbc.com": 0.95,
    "bbc.com/news": 0.93,
    "cnn.com": 0.88,
    "cnn.com/world": 0.87,
    "nytimes.com": 0.94,
    "reuters.com": 0.96,
    "theguardian.com": 0.86,
    "bloomberg.com": 0.89,
    "wsj.com": 0.88,
    "ft.com": 0.87,
    "economist.com": 0.90,
    "apnews.com": 0.88,
    "washingtonpost.com": 0.86,
    "npr.org": 0.90,
    "wikipedia.org": 0.84,
    "arxiv.org": 0.95,
    "nature.com": 0.96,
    "science.org": 0.95,
    "nih.gov": 0.94,
    "who.int": 0.94,
    "cdc.gov": 0.92,
    "un.org": 0.88,
    "worldbank.org": 0.90,
    "imf.org": 0.88,
    "oecd.org": 0.87,
    "gov.uk": 0.90,
    "nhs.uk": 0.92,
    "mayoclinic.org": 0.89,
    "healthline.com": 0.74,
    "webmd.com": 0.70,
    "verywellhealth.com": 0.68,
    "mit.edu": 0.93,
    "stanford.edu": 0.93,
    "cs.cmu.edu": 0.89,
    "github.com/open-source-project": 0.80,
    "docs.python.org": 0.94,
    "pypi.org": 0.76,
    "stackoverflow.com": 0.72,
    "medium.com": 0.60,
    "medium.com/ai": 0.73,
    "towardsdatascience.com": 0.70,
    "kaggle.com": 0.78,
    "substack.com/tech": 0.66,
    "personalblog.dev": 0.58,
    "randomblog123.com": 0.24,
    "clickbaitnews.net": 0.12,
    "forumspam.net": 0.03,
    "login.site.com": 0.02,
    "signup.site.com": 0.02,
    "account.site.com": 0.03,
    "shoppingcart.com": 0.05,
    "checkout.com": 0.01,
    "product123.store/item1": 0.08,
    "product123.store/reviews": 0.06,
}


def get_web_data():
    """Return all experiment data structures."""
    return GRAPH, PAGERANK, ALLOWED, CONTENT_QUALITY


if __name__ == "__main__":
    print(f"Nodes: {len(GRAPH)}")
    print(f"Allowed pages: {len(ALLOWED)}")
